#25 新規issue作成
if-tech-support/todo_team_2 pull request #36
Opened 2022-01-08 13:44 UTC by iamyabui

## IssueのURL
https://github.com/if-tech-support/todo_team_2/issues/25
closes #25 

## 対応内容・対応背景・妥協点
新規issueの作成

## やったこと
このPR内でやったことを書く

## やってないこと・できていないこと
このPR内でやっていないことやできなかったことを書く

## UI before / after
UIや振る舞いが変わる場合はbefore / afterのスクショや動画を共有する

## テスト
テスト項目、テスト方法を書く

## レビュー観点
あくまで目安です。

- 想定通りに動作するか？
- より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- より良い設計方法はないか？
- 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- 関数、コンポーネントの粒度は適切か？
- etc...

## 補足

※必要な項目だけ使用し、不要なものは削除すること

2022-01-13 11:09 UTC, hirooutdoor commented
ナイスプルリクです！
コードレビューの前にまずは以下修正お願いします

- プルリクタイトルは新規issue作成ではなくtodo作成?
- できれば、このプルリクでできなかったことも書きましょう（書ける範囲で結構です）
- 追加でレビューして欲しい観点を自分なりでいいので書いてみてください（特に自信がないと感じる部分や理解が足りていない部分、不明な部分はどこか）

2022-01-13 11:23 UTC, hirooutdoor submitted a review, later dismissed
今できる範囲でしました！レビュー確認お願いします！
UIに関しては一旦、スクショもらってからレビューします！

2022-01-13 11:23 UTC, hirooutdoor commented on pages/_app.js
>  import { ChakraProvider } from '@chakra-ui/react'
ここに変更を加えてない場合は、この差分はコミット/プッシュしないようにしましょう。

2022-01-13 11:23 UTC, hirooutdoor commented on pages/index.js
> +import { NewTodo } from './NewTodo'
新規todo画面の実装で間違えなかったでしょうか？
pages/index.jsは一覧ページになるのでそこにインポートせずに、新たに/pages配下にファイルを作りましょう

https://nextjs-ja-translation-docs.vercel.app/docs/routing/introduction

2022-01-14 08:42 UTC, iamyabui commented
@hirooutdoor さん、
レビューありがとうございます！いろいろと抜け放題で申し訳ありません。。
また、指摘いただいていたindexファイルの修正と新規のnewtodo用のファイルを作成しpushしました。

・見た目の差分を知りたいのでUIのスクショはってください
こちら添付しておらず申し訳ありません。。
![スクリーンショット 2022-01-14 17 10 16](https://user-images.githubusercontent.com/59202001/149478242-a22aebe0-9282-4417-b5c3-91e954494c11.png)

・プルリクタイトルは新規issue作成ではなくtodo作成?
先程タイトルを修正しました。

・できれば、このプルリクでできなかったことも書きましょう（書ける範囲で結構です）
-ボタンの細かい色指定ができず、似た色の指定しかできませんでした。
-おそらくHeader部分はファイルを分けてコンポーネント化したほうがいいのかなと思ったのですが、今回そこまでできていないです。

追加でレビューして欲しい観点を自分なりでいいので書いてみてください（特に自信がないと感じる部分や理解が足りていない部分、不明な部分はどこか）
-UI作成が苦手なので、FlexやBoxの使い方があっているかが不安です。

2022-01-15 11:40 UTC, Junkichi89 requested changes
見た目は問題ないですね！
ただ、yarn.lockに差分が発生するのは問題があるので、nodeのバージョンがプロジェクトで使用しているものと一致しているか確認してもらえますか？
nodeのバージョンはreadmeに記載しています。

2022-01-17 12:37 UTC, Junkichi89 approved these changes
LGTM!

2022-01-17 12:38 UTC, merged