#20 Top画面の右上３つのメインアイコンボタンを追加
if-tech-support/todo_team_2 pull request #45
Opened 2022-01-11 06:25 UTC by mihomihouk

## IssueのURL
close #20 

## 対応内容・対応背景・妥協点
-Top画面右上の３つのアイコンボタンを追加

## やったこと
-@chakra-ui/iconsをインストール
-MainButtons.jsxを作成（test.jsxが他のメンバーによって使用中だったため、コンフリクトを避けるために）
-chakra-uiよりBoxとIconButtonを、chakra-ui/iconsよりDeleteIcon、EditIcon、ExternalLinkIconをインポート

## やってないこと・できていないこと
-コンポーネントの細分化
 	-現時点の仕様書では、本Todoアプリでこれら３つのアイコンボタンを用いるのはTop画面右上の一か所のみ。そのため、本コンポーネントで用いるアイコンボタンをそれぞれ別のatom要素として別々のファイルにまとめる作業はしていない。
-コンポーネントの横幅
	-親コンポーネントによって％で合わせた方がレスポンシブ対応しやすいため、現段階ではあえて設定しない方がよいと考えた。
-ボタンのサイズ
	-こちらも全体とのバランスで後ほど微調整することになるため、現段階ではデフォルト値にしておいた。

ご確認・ご意見よろしくお願い致します。

2022-01-11 12:05 UTC, Junkichi89 requested changes
実装お疲れ様でした。
まず先に以下の内容を行った上で修正をお願いいたします。

1. package-lock.json、node_modulesとyarn.lockを削除して、yarnを実行してください。
2. pages配下に作成した、`pages/MainButtons.jsx`をcomponent化し、`pages/test.jsx`の中身を変更し、作成したコンポーネントを設置してください。
(test.jsxのファイルについては、マージ前に消去するため自由に変更可能です)

上記を行なってから、レビューにて指摘した内容の修正をお願いいたします。
よろしくお願いいたします。

2022-01-11 12:05 UTC, Junkichi89 commented on pages/MainButtons.jsx
> +            <Box display="flex" alignItems="center" justifyContent="space-between">
こちらはbox以外に実現できるコンポーネントがありますので、chakra-uiの公式ドキュメントから探して修正お願いいたします。

2022-01-12 02:36 UTC, mihomihouk commented on pages/MainButtons.jsx
> +        <div>
先の、全体に関わる部分の修正について質問です。
1. package-lock.json、node_modulesとyarn.lockを削除して、yarnを実行してください。
➔package-lock.json、node_modulesとyarn.lockを削除し、yarn runをたたくと、error Command "yarn" not found.とエラーが出ます。この指示の意味を理解しきれているか不安なので、もう少し具体的に教えていただけれると嬉しいです。

2022-01-12 05:13 UTC, mihomihouk commented on pages/MainButtons.jsx
> +        <div>
この点について、
1. 再びyarn install でyarn をインストール
2. yarn dev
で問題なく実行できました。お騒がせしました。

2022-01-12 06:51 UTC, Junkichi89 commented on pages/MainButtons.jsx
> +        <div>
問題なく実装できてよかったです。

`package-lock.json、node_modulesとyarn.lockを削除して、yarnを実行してください。`
ここについては以下の記事を参照してみてください。
https://qiita.com/senou/items/d939601e32c0005ebfe3

2022-01-12 12:48 UTC, mihomihouk commented on pages/MainButtons.jsx
> +        <div>
共有いただいた記事、とても参考になります！ありがとうございます！

ちなみに、修正を加えて再度レビューを申請しなおしたのですが、この場合はレビュワーに再びレビューお願いの通知は行くのでしょうか？もしいかないのであれば、Stackやこちらのコメントで再度レビューをお願いする旨をお伝えした方が良いのでしょうか？

2022-01-12 13:19 UTC, Junkichi89 commented on pages/MainButtons.jsx
> +        <div>
https://w1587112682-vuu114373.slack.com/archives/C02RA8BF0H1/p1641693527014000

こちらご確認ください。

@Junkichi89 のようにメンションしてもらえれば通知は来ると思います。

2022-01-12 23:12 UTC, Junkichi89 requested changes
実装お疲れ様です！

コード整形が行えていないですね。
この辺の記事をご確認いただけますか？
https://qiita.com/mgmgmogumi/items/17438d45790635bd8dca
不明な場合は、チームのメンバーに相談してみましょう！

作成したcomponentファイルのディレクトリを変更してください。
なぜ、今のディレクトリ（pages/MainButtons.jsx）に問題があるのか、自分で一度考えてみて下さい。

他のメンバーに相談してみてもらっても大丈夫です。

よろしくお願いいたします。

2022-01-13 05:33 UTC, mihomihouk commented
ジュンペイさん

丁寧なレビューを毎回ありがとうございます。
コード整形について、{ }内の最前と最後の空白を見落としておりました。
申し訳ありません。
修正しましたので再度ご確認をお願いいたします。

変更点：

1. コード整形
➔import { DeleteIcon, EditIcon, ExternalLinkIcon } from '@chakra-ui/icons'　
2. 作成したMainButtonコンポーネントファイルのディレクトリ変更
➔componentsフォルダの中に、moleculesフォルダを作成
➔作成したMainButtonコンポーネントファイルを、moleculesフォルダ内に移動 (今後、moleculesにいれる他の要素を見ながら追加でディレクトリを作成する流れになると判断し、現時点ではmoleculesの中にはディレクトリを作成していない)

確認よろしくお願いします。

2022-01-13 12:27 UTC, merged