#16 Todo ListのTable作成
if-tech-support/todo_team_2 pull request #46
Opened 2022-01-11 13:22 UTC by insideplant

## IssueのURL
closes #16 

## 対応内容・対応背景・妥協点
![image](https://user-images.githubusercontent.com/78947543/148948911-46574fc3-7f65-4c78-afbe-4923bf528d61.png)

・Todoテーブルを作成　（Thead, Th, Tr, Tbody, Td コンポーネントの使用）
・Taskについては幅を30%取り他のThに比べて表示幅を広く実装

## やったこと
このPR内でやったことを書く

## やってないこと・できていないこと
今後index でcontainerの記述をすることを想定して、横幅は100%に広がるように作成。
TodoをNewする時もTable上のTask表示幅に合わせて文字数制限をかけていくべき。

以上

2022-01-11 22:29 UTC, Junkichi89 requested changes
@insideplant 

実装お疲れ様でした！

表示、コード共にほとんど問題ありませんでした。
ただ、今回はcomponentの作成Issueなので
componentを作成し、test.jsxにimportして、表示させるように修正をお願いいたします。

よろしくお願いいたします。

2022-01-11 22:29 UTC, Junkichi89 commented on pages/test.js
> +          <Th h={7} width="30%">Task</Th>
`h={7}`

こちらの記述は必要でしょうか？

2022-01-12 11:03 UTC, insideplant commented on pages/test.js
> +          <Th h={7} width="30%">Task</Th>
削除忘れてました、訂正します。

2022-01-12 11:06 UTC, insideplant commented
@Junkichi89 
reviewありがとうございます。
下記パスにコードを移動させ、test.jsでコンポーネントを呼び出すように変更いたしました。
src/components/organisms/Todo/TodoTable"

ご確認宜しくお願い致します。

2022-01-12 11:56 UTC, Junkichi89 approved these changes
LGTMです！

test.jsを削除してマージしてください。

![LGTM](https://image.lgtmoon.dev/152759)

2022-01-12 14:58 UTC, insideplant commented
伏線回収ありがとうございますw
承知いたしました！

2022-01-12 15:01 UTC, merged