#12 検索フォームコンポーネント 作成
if-tech-support/todo_team_2 pull request #47
Opened 2022-01-11 15:38 UTC by nao5100000

## IssueのURL

closes #12

## やったこと
・「npm i @chakra-ui/icons」でアイコンをインストール
・atoms / searchの中にSearchForm.jsxを作成して検索フォームコンポーネントを追加
   [img-search](https://user-images.githubusercontent.com/95232038/148972734-2fbb4487-7e15-49a8-a441-60228717ecee.png)

## やってないこと・できていないこと
・入力したテキストに応じたinputのvalue値の取得

2022-01-11 23:25 UTC, Junkichi89 requested changes
mihomihouk さんのIssueでも同様のpackageをインストールしていて、同様の修正を依頼しているので、まずは、こちらのリンクの内容を確認して、修正を優先して行なってください。
https://github.com/if-tech-support/todo_team_2/pull/45#pullrequestreview-849069305

内容が分かりにくい場合は、自分で解決できるように質問をしてください。


コード全体のインデントを揃えられるように、コード整形を行うようにお願いいたします。

指摘内容に沿って、コンポーネントの修正をお願いいたします。

また、test.jsxページを作成して、作成したcomponentをimportしてレビュワーが表示を確認できるようにしてください。

少し長くなりましたが、修正よろしくお願いいたします。
指摘が分かりづらい部分は質問してください。

2022-01-11 23:25 UTC, Junkichi89 commented on src/components/atoms/search/SearchForm.jsx
> +            <InputGroup w={48}>
w={48}は必要でしょうか？
幅などは、親側のコンポーネントで決めていくかと思いますので、こちらでは指定しないで問題ないかと思います。

2022-01-11 23:25 UTC, Junkichi89 commented on src/components/atoms/search/SearchForm.jsx
> +                        <IconButton
IconButtonを使う必要ありますか？

こちらは仕様にも関わる問題かと思うので、MTGでチームメンバーに相談してみますか？

ボタンが必要な場合
- テキスト入力後クリックしてから検索を実行
- 検索用のボタンをデザインに追加してもらう？

ボタンでなくただのアイコンでいい場合
- テキスト入力ごとに検索をかけ、一致するものが表示される


ちょっとこの辺の実装はフロントだけだと大変そうな予感がします・・・

一旦、ボタンではなく、アイコンの実装で進めてください。

2022-01-12 12:27 UTC, nao5100000 commented
レビューありがとうございます。

ご指摘いただいた箇所の修正を実施しましたので、
再度ご確認お願いいたします。

2022-01-12 12:54 UTC, Junkichi89 requested changes
@nao5100000 
以下を必ず実行してください。
package-lock.json、node_modulesとyarn.lockを削除して、yarnを実行してください。

![image](https://user-images.githubusercontent.com/65665381/149143452-bdd281fd-4e08-423d-a4ee-61ac0f2cfc4b.png)

eslintのエラーが出たままなので、一旦ルールをoffにしてしもらえますか？
`.eslintrc.js`
上記ファイルのruleの中に以下を設定してください。

'react/no-children-prop': 'off',

コードの整形も行ってもらえますか？
alt(option) + shift + f で実行できませんか？

2022-01-12 16:19 UTC, nao5100000 commented
すみません...
見落としてました..
ご指摘いただい箇所の修正を実施しましたので、再度ご確認お願いいたします。

2022-01-12 22:56 UTC, Junkichi89 approved these changes
実装お疲れ様です！
LGTMです！！

![LGTM](https://image.lgtmoon.dev/152779)

test.jsxを削除してマージしてください。

2022-01-13 13:14 UTC, merged