#18 todo list status component
if-tech-support/todo_team_2 pull request #53
Opened 2022-01-15 11:15 UTC by washogo

## IssueのURL
https://github.com/if-tech-support/todo_team_2/issues/18#issue-1094318857

## 対応内容・対応背景・妥協点
Todo一覧画面の絞り込みに使用するStatusのselectを作成

## やったこと
デザイン画像を参考にして、Todo一覧画面のStatusのselectをラベルと共に作成

## やってないこと・できていないこと
機能の実装

## UI before / after

https://user-images.githubusercontent.com/89339695/149619714-8db0d25d-9f76-4e2c-98d9-e9c1b1d193f4.mov

## テスト

## レビュー観点
あくまで目安です。

- 想定通りに動作するか？
- より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- より良い設計方法はないか？
- 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- 関数、コンポーネントの粒度は適切か？
- etc...

## 補足

※必要な項目だけ使用し、不要なものは削除すること

2022-01-15 11:35 UTC, Junkichi89 requested changes
componentを作成して、pages/test.jsxファイルでimportしましょう！
他のプルリクエストでも同様の指摘をしています。
意図がわからない場合は、メンバーに相談してください。

2022-01-15 11:39 UTC, washogo commented
> componentを作成して、pages/test.jsxファイルでimportしましょう！ 他のプルリクエストでも同様の指摘をしています。 意図がわからない場合は、メンバーに相談してください。

分りました！ありがとうございます。

2022-01-16 05:01 UTC, washogo commented
StatusSearchコンポーネントを作成してtest.jsxにインポートした後に、レイアウトを微調整しました。ご確認鎧苦お願い致します。

2022-01-17 13:32 UTC, Junkichi89 requested changes
@washogo 
遅くなりました。

修正をお願いいたします！

2022-01-17 13:32 UTC, Junkichi89 commented on pages/index.js
> +      <Head></Head>
ここの変更は不要なので、remoteのmainをpullしてそちらに合わせましょう。

2022-01-17 13:32 UTC, Junkichi89 commented on pages/test.jsx
> +    <SearchStatus></SearchStatus>
セルフクロージングタグを使いましょう！

2022-01-17 13:32 UTC, Junkichi89 commented on src/components/atoms/search/SearchStatus.jsx
> +    </FormControl>
コード整形が行えていないので、整形してから提出するように心がけましょう！

2022-01-19 14:09 UTC, london-newyork commented on src/components/atoms/search/SearchStatus.jsx
> +    </FormControl>
こちら、おそらくSelectのタグやFormLabelのタグの中で、プロパティごとに折り返す必要があるのではないでしょうか？

```
<Select
 id='status'
 fontFamily='Gothic A1'
```

2022-01-20 11:55 UTC, washogo commented
教えていただいてありがとうございます！
SearchStatus.jsxの修正を行いましたので、確認お願いします。

2022-01-20 15:07 UTC, Junkichi89 approved these changes
LGTM !!!!

![LGTM](https://image.lgtmoon.dev/153591)

2022-01-21 15:22 UTC, merged