#23 comment component
if-tech-support/todo_team_2 pull request #74
Opened 2022-01-20 10:33 UTC by iamyabui

## IssueのURL
https://github.com/if-tech-support/todo_team_2/issues/23

## 対応内容・対応背景・妥協点
コメントのUIを作成しました。

## やったこと
・コメント内名前と投稿日表示部分UI
・コメント記載部分UI

## やってないこと・できていないこと
・投稿後に渡された値（名前と日付）の表示（機能部分で実装するため）
・BoxにborderColorで枠線を入れようとしても、反映されずそこだけできていないです。。

## UI before / after

![スクリーンショット 2022-01-20 19 29 43](https://user-images.githubusercontent.com/59202001/150321553-3300e35c-05ef-4ff3-9500-3f11ccc8e9fa.png)

## テスト
実施なし

## レビュー観点

## 補足

2022-01-22 09:19 UTC, london-newyork reviewed
レビューしました〜お願いいたします！

2022-01-22 09:24 UTC, london-newyork requested changes
レビューしましたのでよろしくお願いいたします！

2022-01-22 09:24 UTC, london-newyork commented on pages/test.jsx
> +      <Box borderRadius="8px" borderWidth="1px" w="400px" h="100px">
その他にはなさそうです！

2022-01-23 23:12 UTC, iamyabui commented
＞Boxにborder="1px" borderColor=""を設置すると良さそうです。borderWidthはいらないですね。
こちらについて修正し、mainからpull後のconflict部分をlocalで修正してpushしました！
mergeをお願いします。

2022-01-24 02:33 UTC, london-newyork commented
どうやら他のIssue（new Todo）の内容もPRに混ざってしまっているようです。
できればPRを分けたほうが良さそうに思うのですが、どうでしょう・・

2022-01-24 02:34 UTC, london-newyork requested changes
わかるところのみレビューしました。
よろしくお願いいたします！

2022-01-24 02:34 UTC, london-newyork commented on src/components/atoms/comment/comment.jsx
> +          color="white"
flexに対してpr plを設定するのであれば、その子コンポーネントの「テキスト」の周りを「box」で囲まなくていいのではないかなと思います。text自体がPタグでブロック要素のようです。
若干paddingの値が多めな感じがするのでpaddingは小さめの数値にしましょう。

2022-01-24 02:34 UTC, london-newyork commented on src/components/atoms/comment/comment.jsx
> +          <Spacer />
spacerがいらないかもですね。

2022-01-24 02:41 UTC, london-newyork commented on src/components/atoms/comment/comment.jsx
> +          color="white"
justifyContent="space-between"を入れてみてください

2022-01-24 09:11 UTC, iamyabui commented on src/components/atoms/comment/comment.jsx
> +          color="white"
ありがとうございます！以下修正しておきました。
・boxの削除
・paddingの値を小さくしました
・spacerは消して、justifyContent="space-between"に変更しました

2022-01-24 09:12 UTC, iamyabui commented on src/components/atoms/comment/comment.jsx
> +          <Spacer />
spacerも消しておきました！

2022-01-24 10:43 UTC, london-newyork approved these changes
OKだと思います！お疲れ様でした〜！

2022-01-29 13:47 UTC, closed without merging