#37 priority ラジオボタン作成
if-tech-support/todo_team_2 pull request #79
Opened 2022-01-22 08:27 UTC by nao5100000

## IssueのURL
#37 closes

## 対応内容・対応背景・妥協点
Todoタスク作成画面のpriorityラジオボタンを作成

## やったこと
・Hight、Middle、Lowのラジオボタンを作成

## やってないこと・できていないこと
・UIのみなので、選択した値をTodo一覧に反映等の機能はまだ実装していません。

## UI before / after
![priorityRadio](https://user-images.githubusercontent.com/95232038/150630942-209fdc90-066b-43df-881d-0cd8cc2fba57.png)

2022-01-23 22:36 UTC, ayakamiyake7 requested changes
とても良いと思います！ラジオボタンの文字の太さについて指摘させていただきました！
ご確認お願いいたします！

2022-01-23 22:36 UTC, ayakamiyake7 commented on src/components/atoms/input/RadioPriority.jsx
> +        <Stack direction="row" spacing={8}>
文字の太さをデザインに揃えると良いかもしれません、細かくてすみません…

2022-01-24 12:04 UTC, nao5100000 commented
レビューありがとうございます！
確かに比べてみるとウェイト細かったですね..！
太くしてみましたので、ご確認お願いいたします

2022-01-24 13:22 UTC, ayakamiyake7 approved these changes
確認しました、マージお願いいたします！

2022-01-25 10:26 UTC, merged