#68 create機能を作成
if-tech-support/todo_team_2 pull request #89
Opened 2022-01-30 13:20 UTC by insideplant

## IssueのURL
close #68 

## 対応内容・対応背景・妥協点
・Create機能の追加

## やったこと
①/src/hooks/userState.jsというファイル構造を作り、recoilのフックスを作成しrecoilPersistで値の永続化。
②/src/hooks/Now.jsというファイル構造を作り、現在時刻を取得するフックスを作成
③各tile,detail,priority等の引数となる変数をuseStateで定義。
④onSubmitファンクションにて②の値でsetTodoでcreate処理

動作
・値を入力
・入力された値を保持
・createボタンを押すとtodosに値を保持
・値を保持したまま一覧ページへ遷移する

## やってないこと・できていないこと
BackButtonコンポーネントでエラーが出ており、解決出来ないので取り敢えずコメントアウトしております。

## UI before / after
![image](https://user-images.githubusercontent.com/78947543/151701312-bebbf034-2d6e-4aa1-b6b8-07f5a52ef289.png)

2022-01-31 04:00 UTC, london-newyork requested changes

2022-01-31 04:00 UTC, london-newyork commented on pages/Newtodo.jsx
> +          <RadioPriority setPriority={setPriority} />
すみません、今週のレビュアーなのでレビューしてみます。
素人質問よろしいでしょうか。
propsとして渡ってくる名前や中身がsetTitle={setTitle}やsetDetail={setDetail} setPriority={setPriority}というのが見慣れない感じがするのですが、titleや詳細テキストエリア、radioボタンのデータを保持して、そのデータを反映するみたいな意味ですか？

2022-01-31 09:24 UTC, insideplant commented on pages/Newtodo.jsx
> +          <RadioPriority setPriority={setPriority} />
子コンポーネントにstateの更新関数をpropsに引き渡してます。ですので、子コンポーネントを見て頂くと、propsから更新関数も取得していることが分かると思います。

2022-02-01 01:02 UTC, mihomihouk reviewed
レビューしました！ご確認お願いします！

2022-02-01 10:50 UTC, insideplant commented on pages/Newtodo.jsx
> -import { BackButton } from '../src/components/atoms/button/BackButton'
ありがとうございます！
修正しておきます。

2022-02-01 11:21 UTC, insideplant commented on pages/Newtodo.jsx
> +  const [priority, setPriority] = useState('High')
ご指摘ありがとうございます。勝手にradioPriorityも①の使用で既に作られていると認識してしまってました💦
しかしながら、やはりユーザーに意識的に選択して貰いたいので②の仕様にするように変更します！

余裕があれば、今後のIssueで入力、選択していなければバリデーションでエラー表示するように実装する所まで進めたいですね(^^)！！

2022-02-01 11:30 UTC, insideplant commented
修正いたしました！再レビューお願い致します<(_ _)>

2022-02-02 07:46 UTC, mihomihouk requested changes
@insideplant 
イベント発生後、todosにはちゃんとキーも値も入っていて、遷移も問題ないと思います。
1点だけ気になる箇所がありますので、ご確認いただけると嬉しいです。

2022-02-02 07:46 UTC, mihomihouk commented on pages/Newtodo.jsx
> +    // e.preventDefault()
@insideplant 
このe.preventDefaultはなぜコメントアウトされているのですか？

2022-02-02 09:55 UTC, insideplant commented on pages/Newtodo.jsx
> +    // e.preventDefault()
当初 e.preventDefault()の記載が必要と思い書いておりました。
改めて考え直し、不要と思いコメントアウトしましたが削除を忘れておりました。

正直ここについて、あまり自身が無いのですが、、、、
今回<form>タグを用いておりませんので、元々requestを走らせる処理が初期で無いので今回はいらないと考えております。

2022-02-02 13:35 UTC, mihomihouk commented on pages/Newtodo.jsx
> +    // e.preventDefault()
＠ジュンペイ
この点いかがでしょうか？

https://qiita.com/tochiji/items/4e9e64cabc0a1cd7a1ae
この記事の通り、e.preventDefault()が、inputの「submit」での「click」イベント時、「actionで指定されたURLへ遷移＋データ送信」されるのをあえて「防ぐ」のであれば、今回の実装においてe.preventDefault()を書く必要はないと思うのですが...私も自信がないです。

2022-02-02 14:44 UTC, Junkichi89 commented
連絡いただいた箇所以外にも気になったのでいろいろとレビューさせていただきました。
確認お願いいたします。

2022-02-02 14:47 UTC, Junkichi89 reviewed
@insideplant @washogo cc @mihomihouk 

連絡いただいた箇所以外にも気になったので、レビューさせていただきました。
ご確認お願いいたします。

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +  const { todos, setTodos } = TodoState()
これカスタムHookにする必要ありますか？
https://reffect.co.jp/react/react-custom-hook
https://ja.reactjs.org/docs/hooks-custom.html

また、カスタムHookを作る際は、useStateと体裁を合わせるためにuse〜という関数名にするのが一般的かと思います。
（公式にもuseで始まりと書いてあります）

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +  const quantity = Object.keys(todos).length
この定数を作成する理由が知りたいです。
教えてください。

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +  console.log(todos)
プルリク投げる際はなるべくデバック用のログは消しましょう。

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +    // e.preventDefault()
不要です！消しましょう！

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +    setDetail('')
setTitleとsetDetalの初期化いらない気がしますが、どうでしょうか？

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +  const { currentTime } = Now()
hooksじゃないですね。
ディレクトリ分けるならutilsとかの方が適切かと。
あと、Nowだと何をする関数なのかわかりません。

2022-02-02 14:47 UTC, Junkichi89 commented on pages/Newtodo.jsx
> +  const id = quantity + 1
これだとIDかぶっちゃいますよね？

2022-02-02 15:33 UTC, insideplant commented on pages/Newtodo.jsx
> +  const { todos, setTodos } = TodoState()
おっしゃる通りです！カスタムhookは無駄な記述でした、、、
また、カスタムhookの命名につきましても理解致しました。
ありがとうございます。

2022-02-02 15:38 UTC, insideplant commented on pages/Newtodo.jsx
> +  const id = quantity + 1
よくよく考えると確かにです、、、最考致します。

2022-02-02 15:49 UTC, insideplant commented on pages/Newtodo.jsx
> +    setDetail('')
ページ遷移するので不要でした、ご指摘ありがとうございます。

2022-02-02 15:49 UTC, insideplant commented on pages/Newtodo.jsx
> +  console.log(todos)
削除致します。

2022-02-02 15:51 UTC, insideplant commented on pages/Newtodo.jsx
> +  const quantity = Object.keys(todos).length
定数化する必要は無かったですが、自身としても処理が理解できるよう分解して記載しました、、、
そもそも下で指摘いただいた通りロジックとして不十分でしたね、、、再考致します。

2022-02-02 15:51 UTC, insideplant commented on pages/Newtodo.jsx
> +    // e.preventDefault()
削除致します。

2022-02-02 21:45 UTC, Junkichi89 commented
![LGTM](https://image.lgtmoon.dev/155161)

LGTMですが、コンフリクト発生しているので、ローカルでpullしくコンフリクト解消してください。

@mihomihouk @london-newyork 
2人の承認がないとマージできないと思いますので、承認よろしくお願いします。

2022-02-03 11:23 UTC, mihomihouk commented
@insideplant @Junkichi89 
ジュンペイさん、レビューありがとうございました。
なかうえさん、修正ありがとうございます！
承認いたします。

2022-02-03 11:23 UTC, mihomihouk approved these changes

2022-02-03 11:31 UTC, london-newyork approved these changes
問題ないと思います!

2022-02-03 12:13 UTC, merged